### ISSUE TITLE
auto close datepicker upon selection

### ISSUE THREAD

**Issue by matrixall** [abublihi/datepicker-hijri#1]
thx for the great work. it needs auto close after selecting desired date. plz consider adding such option or necessity.

**Comment by abublihi** [comment]
Thank you for your interest, I will add this option and it will be very soon (ان شاء الله)

**Comment by matrixall** [comment]
I'm always in a hurry so I kept playing with codes till I found a work around by binding click on day button to a click anywhere in my document that solved the issue for now. waiting for your elegant solution (بالتوفيق)

**Comment by abublihi** [comment]
Now You can close the date picker upon selection  by adding the `on-date-select-close` attribute
```html
<datepicker-hijri reference="calender" placement="bottom" selected-date="1441/02/01" on-date-select-close></datepicker-hijri>````
